server:
  port: 8082

spring:

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/intouch_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: false
    default-schema:

springdoc:
  override-with-generic-response: false


security:
  jwt:
    secret: ${SECRET}
    access: 3600000
    refresh: 2592000000

minio:
  bucket: images
  url: http://localhost:9000
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
