spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: post-microservice
          uri: lb://post-microservice
          predicates:
            - Path=/post/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8080